application:
  actions: actions
  runtimeManifest:
    packages:
      aemcs-assets-slack-webhook:
        license: Apache-2.0
        actions:
          asset-events-slack-webhook:
            function: actions/asset-events-slack-webhook/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
